Pacify mypy 0.790 for NotImplemented returns
Mypy 0.790 complains that:

apt/package.py:473: error: Variable "builtins.NotImplemented" is not valid as a type
apt/package.py:473: note: See https://mypy.readthedocs.io/en/latest/common_issues.html#variables-vs-type-aliases

This worked fine in 0.782.

As a workaround, use Any instead of NotImplemented. Ugh

See https://github.com/python/mypy/issues/4791 for more
information.